### ISSUE TITLE
GitHub Actions实现SpringBoot打包及部署

### ISSUE THREAD

**Issue by licoded** [licoded/self-study-record#31]
### 需要设置的环境变量

1. HOST
2. PASSWORD
3. USERNAME

### 配置文件

```yml
name: package-and-deploy
on:
  push: # 在代码提交时自动触发
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for package
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: package
        run: |
          mvn --batch-mode package
      - name: Set env
        run: |
          echo "PACKAGE_JAR=$(ls -l target | grep '.jar$' | awk '{print $NF}')" >> $GITHUB_ENV
          echo $PACKAGE_JAR
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "target/${{ env.PACKAGE_JAR }}"
          target: "/home/${{ secrets.USERNAME }}/jar"
      - name: executing remote ssh commands
        # 使用appleboy/ssh-action@master来执行命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/jar
            mv target/${{ env.PACKAGE_JAR }} ${{ env.PACKAGE_JAR }}
            rm -rf target
            echo ${{ secrets.PASSWORD }} | sudo -S service my-java-hualihushao restart
```

## 注册 jar 文件到 Ubuntu 系统服务

```bash
sudo vim /etc/systemd/system/my-java-xxx.service
sudo systemctl daemon-reload
# 利用管道实现密码自动输入
echo <password> | sudo -S service my-java-xxx restart
```

### 使用前提

1. 需要创建 `path/to/log` 文件夹
4. 需要配置 java 环境

**my-java-xxx.service**文件内容如下

```service
[Service]
User=<username>
# The configuration file application.properties should be here:

#change this to your workspace
WorkingDirectory=path/to/jar

#path to executable.
#executable is a bash script which calls jar file
ExecStart=/usr/bin/java -jar path/to/jar/xxx-0.0.1-SNAPSHOT.jar

StandardOutput=file:path/to/logs/xxx/stdout.log
StandardError=file:path/to/logs/xxx/stderr.log

SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
